name: Linting all code
on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  lint-prettier:
    name: Lint-prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          show-progress: false
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{hashFiles('package.json')}}
          restore-keys: node_modules-
      - name: npm install
        run: npm install
      - name: stylelint
        run: npm run lint:prettier
  lint-styles:
    name: Lint-styles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          show-progress: false
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{hashFiles('package.json')}}
          restore-keys: node_modules-
      - name: npm install
        run: npm install
      - name: stylelint
        run: npm run lint:styles
  lint-scripts:
    name: Lint-scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          show-progress: false
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{hashFiles('package.json')}}
          restore-keys: node_modules-
      - name: npm install
        run: npm install
      - name: stylelint
        run: npm run lint:scripts
  lint-knip:
    name: Lint-knip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          show-progress: false
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{hashFiles('package.json')}}
          restore-keys: node_modules-
      - name: npm install
        run: npm install
      - name: check-knip
        run: npm run lint:knip